# FOMO25 Container Configuration
# ----------------------------

# Container settings
container:
  # Container name (without extension)
  name: "fomo25-container"
  
  # Apptainer/Singularity command
  command: "apptainer"                            
  

# Directory paths
directories:
  # Input data location
  input: "test/input"
  
  # Results location
  output: "test/output"

  # Container storage location
  containers: "apptainer-images"                    
  

# Build settings
build:
  # Model source code
  source: "src"                                     
  
  # Container definition file
  definition: "Apptainer.def"                       
  

# Validation settings
validate:
  # Use GPU if available
  gpu: true     

  # Create synthetic test data
  generate_data: true                                 
  
  # Calculate performance metrics
  compute_metrics: true                               
  
  # Generate validation report
  save_report: true                                   
  
  # Report output file
  result_file: "validation_result.json"
